name: Build the API
on:
  push:
    tags:
      - "[1-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          java-version: '17'

      - name: Build jars with Gradle
        run: |
          gradle shadowJar
          gradle javadocJar
          gradle sourcesJar

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: "Release ${{ env.TAG }}"
          body: "Automatic release"
          draft: true
          prerelease: false

      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: build/libs

      # - name: Upload Artifact
      #   id: upload-release-asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     TAG: ${{ github.ref_name }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./build/libs/JGA-${{ env.TAG }}.jar
      #     asset_name: JGA-${{ env.TAG }}.jar
      #     asset_content_type: application/java-archive